stages:
  - gitlab-registry-build
  - dockerhub-build
  # - docker-compose-deploy
  - kubernetes-deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

gitlab-registry-build:
  stage: gitlab-registry-build
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - echo $IMAGE_TAG
    - docker push $IMAGE_TAG
  tags:
    - docker
  only:
    - main

dockerhub-build:
  stage: dockerhub-build
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t sorokin21/nodejs_test_crud-my_app:latest . 
    - docker push sorokin21/nodejs_test_crud-my_app:latest
  only:
    - main

# docker-compose-deploy:
#   stage: docker-compose-deploy
#   image: docker/compose:1.29.2
#   script:
#     - echo "Deploying using Docker Compose..."
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker-compose up -d
#   only: 
#     - main

kubernetes-deploy:
  stage: kubernetes-deploy
  script:
    - echo "Deploying using kubernetes..."
    - docker login -u sorokin21 -p xtkjdtrgfer01
    - minikube start --driver=docker
    - minikube addons enable logviewer
    - kubectl config use-context minikube
    - kubectl apply -f ./manifests/
  only: 
    - main 