global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'my_app'
    static_configs:
      - targets: ['my_app:4000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'app-exporter'
          group: 'testing'
          name: 'app-exporter'
    