apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatops-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatops-db
  template:
    metadata:
      labels:
        app: chatops-db
    spec:
      containers:
        - name: chatops-db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_DB
              value: debug
          ports:
            - containerPort: 5432
          volumes:
            - name: chatops-data
              mountPath: /var/lib/postgresql/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: sorokin21/nodejs_test_crud-my_app:latest
          ports:
            - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-html
              mountPath: /etc/nginx/html
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-html
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: chatops-db-service
spec:
  selector:
    app: chatops-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80