name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs_test_crud-my_app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs_test_crud-my_app:latest


  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Set up minikube
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      # - name: Start minikube
      #   run: minikube start --vm-driver=docker
      # - name: Set up kubectl
      #   run: |
      #     mkdir -p ~/.kube
      #     touch ~/.kube/config
      #     minikube kubectl -- get pods
      - name: create configMaps
        run: kubectl create configmap nginx-config --from-file=./nginx.conf --dry-run=client &&
             kubectl create configmap nginx-html --from-file=./index.html --dry-run=client

      - name: Deploy application
        run: kubectl apply -f ./manifests/deployment.yaml
