server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - my_app
        labels:
          job: nginx
          __path__: /usr/src/app/logs/nginx/*.log

  - job_name: my_app
    static_configs:
      - targets:
          - my_app
        labels:
          job: my_app
          __path__: /usr/src/app/logs/app/*.log
