server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fluentd
    static_configs:
      - targets:
          - fluentd
        labels:
          job: fluentd
          __path__: /fluentd/bufer/*log
